# Generated by Django 4.2.20 on 2025-03-29 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("boardgames", "0002_alter_event_options_alter_event_game_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoardGameGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="boardgame",
            name="genre",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="boardgames.boardgamegenre",
            ),
        ),
    ]
